### ISSUE TITLE
Version 8.0 odoo osv import failed - is it fixed in this version

### ISSUE THREAD

**Issue by nick26** [enapps/ea_import#15]
I have issue when I install ea_import 

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 394, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 398, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/opt/odoo/openerp/http.py", line 1310, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/addons/ea_import/__init__.py", line 21, in <module>
    import ea_import_template
  File "/opt/odoo/addons/ea_import/ea_import_template.py", line 21, in <module>
    from osv import osv
ImportError: No module named osv

**Comment by Nazarii** [comment]
Hello, nick26, this module requires 6.1 or 7.0 server versions, it will not work with 8.0.

**Comment by nick26** [comment]
I made all the changes and was able to import the module into the odoo 8.
But I have not tested it any further, as I am still new to odoo, in next
couple of day I will test it according to you video. If all is well then I
can submit the code.

thanks
nick

ps. one thing I want to ask you can you use this tool to import products
with variant data
